<?php
// Tanzania Regions and Districts Data
$regions_districts = [
    'Arusha' => [
        'Arusha City',
        'Arusha District',
        'Karatu',
        'Longido',
        'Meruishi',
        'Moshi',
        'Ngorongoro',
        'Same',
    ],
    'Dar es Salaam' => [
        'Ilala',
        'Kinondoni',
        'Kigamboni',
        'Ubungo',
        'Temeke',
    ],
    'Dodoma' => [
        'Bahi',
        'Chamwino',
        'Dodoma City',
        'Dodoma District',
        'Iringa',
        'Kondoa',
        'Kongwa',
    ],
    'Geita' => [
        'Bukombe',
        'Geita',
        'Nzega',
        'Ushetu',
    ],
    'Gombe' => [
        'Gombe City',
        'Gombe District',
        'Kamango',
        'Kaskazini A',
        'Kaskazini B',
    ],
    'Iringa' => [
        'Iringa City',
        'Iringa District',
        'Mbeya',
        'Mufindi',
        'Njombe',
    ],
    'Kagera' => [
        'Biharamulo',
        'Bukoba City',
        'Bukoba Rural',
        'Karagwe',
        'Kyerwa',
        'Muleba',
        'Missenyi',
    ],
    'Katavi' => [
        'Mpanda',
        'Sumbawanga',
        'Tanganyika',
    ],
    'Kigoma' => [
        'Bariadi',
        'Kibondo',
        'Kigoma City',
        'Kigoma District',
        'Ujiji',
    ],
    'Kilimanjaro' => [
        'Hai',
        'Kahe',
        'Mbeya',
        'Moshi City',
        'Moshi District',
        'Same',
        'Siha',
    ],
    'Lindi' => [
        'Lindi City',
        'Lindi District',
        'Mtwara',
        'Nachingwea',
        'Newala',
        'Tandahimba',
    ],
    'Mbeya' => [
        'Chunya',
        'Kyela',
        'Mbeya City',
        'Mbeya District',
        'Mbozi',
        'Momba',
        'Rungwe',
    ],
    'Morogoro' => [
        'Gairo',
        'Morogoro City',
        'Morogoro District',
        'Kilombero',
        'Mvomero',
        'Ulanga',
    ],
    'Mtwara' => [
        'Mtwara City',
        'Mtwara District',
        'Newala',
        'Tandahimba',
    ],
    'Mwanza' => [
        'Bariadi',
        'Bukombe',
        'Mwanza City',
        'Mwanza District',
        'Kwimba',
        'Nyamagana',
        'Sengerema',
    ],
    'Njombe' => [
        'Makambako',
        'Njombe City',
        'Njombe District',
        'Wanging\'omba',
    ],
    'Pemba North' => [
        'Chake Chake',
        'Micheweni',
        'Mkoani',
        'Wete',
    ],
    'Pemba South' => [
        'Chake Chake',
        'Mkoani',
    ],
    'Pwani' => [
        'Bagamoyo',
        'Chalinze',
        'Kunduchi',
        'Pangani',
        'Saadani',
        'Wbagamoyo',
    ],
    'Ruvuma' => [
        'Binga',
        'Mbeya',
        'Mbinga',
        'Songea',
        'Tunduru',
    ],
    'Shinyanga' => [
        'Bariadi',
        'Bukombe',
        'Shinyanga City',
        'Shinyanga District',
        'Kishapu',
        'Nzega',
    ],
    'Simiyu' => [
        'Bariadi',
        'Busega',
        'Liwale',
        'Moshi',
    ],
    'Singida' => [
        'Iramba',
        'Ikungi',
        'Manyoni',
        'Singida City',
        'Singida District',
        'Usangu',
    ],
    'Tabora' => [
        'Igunga',
        'Kaliua',
        'Tabora City',
        'Tabora District',
        'Urambo',
        'Uyui',
    ],
    'Tanga' => [
        'Bumbuli',
        'Korogwe',
        'Lushoto',
        'Muheza',
        'Tanga City',
        'Tanga District',
        'Vanga',
    ],
    'Unguja North' => [
        'Chake Chake',
        'Chwaka',
        'Nungwi',
        'Zanzibar City',
    ],
    'Unguja South' => [
        'Chake Chake',
        'Kizimkazi',
        'Makunduchi',
    ],
    'Zanzibar City' => [
        'Stone Town',
        'Wumbvu',
    ],
];
?>
